Add semantic html elements
sano2019/portfolio_react pull request #6
Opened 2022-10-05 13:43 UTC by Hariprasad19036

2022-10-16 19:55 UTC, sano2019 requested changes
The addition of semantic html should not change the look and styling of the site. Currently my name is added as a header and I think the footer look also changed.

In addition, there is a new master branch so please pull that before doing changes :)

2022-10-16 20:58 UTC, EmmaDawsonDev commented on src/components/layout/Footer.jsx
> +    <footer>
```suggestion
    <footer className=‘footer’>
```

2022-10-16 20:59 UTC, EmmaDawsonDev commented on src/components/layout/Navbar.jsx
> +    <nav>
```suggestion
    <nav className=‘navbar’>
```

2022-10-16 21:00 UTC, EmmaDawsonDev requested changes
The elements are now semantic but there’s no need to remove the classes as that affects the styling. Please add all css back.

2022-10-17 13:46 UTC, Hariprasad19036 commented
> The addition of semantic html should not change the look and styling of the site. Currently my name is added as a header and I think the footer look also changed.
> 
> In addition, there is a new master branch so please pull that before doing changes :)

Do you want me to change the header text / style? If yes what shall I change it to?

2022-10-17 14:06 UTC, sano2019 commented
@Hariprasad19036 

Basically, there was already a <header> element in the site, the "Welcome" is wrapped in it. Therefore there is no need to have the header at the top you are creating.

The only thing you needed to do is change the <div className="footer"> and the same for the nav bar into their proper semantic html elements with the same styling. I think in a previous commit you also removed the styling for the footer as it looks different in the version you are working on than it does in the one running online. 

Also in the latest PR it seems you are using back ticks (´) for the class names, this is preventing me from building the app. Should use single quotes (') :)

2022-10-18 13:25 UTC, Hariprasad19036 commented
@sano2019 Made the specified changes. Kindly review.

2022-10-22 12:04 UTC, sano2019 commented
Thank you @Hariprasad19036 :) Accepted and merging now.

2022-10-22 12:05 UTC, merged