Add aria labels for project cards
sano2019/portfolio_react pull request #9
Opened 2022-10-06 09:08 UTC by Vinitvh

Added aria-labels to links to differentiate for screen reader users. closes #5

2022-10-16 19:31 UTC, sano2019 requested changes
I think the title is sufficient, you can remove the word "website" and "github" from the aria label as it is already implied by the screen reader that it is a link.

After this I will approve it :)

2022-10-16 19:50 UTC, EmmaDawsonDev commented
> I think the title is sufficient, you can remove the word "website" and "github" from the aria label as it is already implied by the screen reader that it is a link.
> 
> After this I will approve it :)

Website and GitHub is needed in the aria label for these as otherwise both links would announce the same thing yet they take you to different places.

2022-10-16 21:01 UTC, EmmaDawsonDev approved these changes

2022-10-17 08:29 UTC, sano2019 commented
> I think the title is sufficient, you can remove the word "website" and "github" from the aria label as it is already implied by the screen reader that it is a link.
> 
> After this I will approve it :)

Yep, I did not read my own code correctly :) My bad, accepting now

2022-10-17 08:29 UTC, merged